[book]
title = "Tonc - GBA Programming in rot13"
description = "GBA Programming tutorial"
src = "content"
language = "en"

[build]
build-dir = "output"
create-missing = false

[output.html]
git-repository-url = "https://github.com/gbadev-org/tonc"
edit-url-template = "https://github.com/gbadev-org/tonc/edit/master/{path}"
site-url = "/tonc/"

[preprocessor.toc]
command = "cargo run -p mdbook-toc --locked --release --"
# Doesn't seem to work because of how markdown parses this as an unresolved shorthand link.
# Default marker is <!-- toc -->
# marker = "[TOC]"
renderer = ["html"]
max-level = 2

[preprocessor.external-links]
command = "cargo run -p mdbook-external-links --locked --release --"

[preprocessor.xnos]
command = "python3 -X utf8 ./mdbook-xnos/mdbook-xnos.py"
